spring.datasource.url=jdbc:postgresql://localhost:5432/movies_db
spring.datasource.username=movie_user
spring.datasource.password=movie123

tmdb.api.key=831ab62fb95a5a36efad423966caa4f2
tmdb.api.url=https://api.themoviedb.org/3

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true