# Project
spring.application.name=backend
spring.profiles.active=local

# Banco de dados
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.properties.hibernate.format_sql=true

# Dialeto (opcional nas versões mais recentes)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect